apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-books-pv
spec:
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cifs
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: 10.71.71.19/podVolumes/calibre/books
    volumeAttributes:
      source: "//10.71.71.19/podVolumes/calibre/books"
    nodeStageSecretRef:
      name: immich-secret
      namespace: default
    fsType: cifs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  volumeMode: Filesystem
  volumeName: calibre-books-pv
  storageClassName: cifs


