{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calibre-web.fullname" . }}-secret
  labels:
    app: {{ include "calibre-web.name" . }}
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
{{- end }}

