{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: calibre-web-secret
  labels:
    app: calibre-web
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
{{- end }}

