radarr:
  metrics:
    main:
      enabled: false
  persistence:
    torrents:
      enabled: true
      type: nfs
      path: /mnt/Storage/things
      server: 10.71.71.19
      targetSelector:
        main:
          main:
            mountPath: /torrents

