apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator-single
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: "0.23.0"
    helm:
      parameters:
        - name: config.clusterWide
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      selfHeal: true

