
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: Kustomize
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alnav3/argocd-charts
    path: kustomization
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
