apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-internal
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alnav3/argocd-charts
    path: system/nginx-internal
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true

