apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-csi/csi-driver-smb
    path: charts/latest/csi-driver-smb
    targetRevision: HEAD
    # Optional: you can specify custom values here if needed
    helm:
      parameters:
        - name: replicaCount
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

