apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://tccr.io/truecharts
    chart: jackett
    targetRevision: "2024.6.3" # Specify the chart version
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

