apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alnav3/argocd-charts
    path: media/jackett/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default


