apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: tccr.io/truecharts
    chart: jackett
    targetRevision: 23.2.2 # Specify the chart version
    helm:
      valueFiles:
        - "https://raw.githubusercontent.com/alnav3/argocd-charts/main/media/jackett/values.yaml" # URL to your GitHub or Git repository
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alnav3/argocd-charts
    path: media/jackett/
    targetRevision: HEAD
    helm:
      valueFiles:
        - secrets://secrets.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default


