apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alnav3/argocd-charts
    path: homelab/charts/transmission/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default

