apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress-external
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sonarr.alnav.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress-internal
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - "*.home"
    secretName: home-cert
  rules:
  - host: sonarr.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989

