{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "libsql-server.fullname" . }}-ingress
  labels:
    app: {{ include "libsql-server.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "libsql-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}

