apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
spec:
  project: default
  source:
    repoURL: https://github.com/alnav3/argocd-charts
    path: /charts/homelab-apps/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: home-apps
  syncPolicy:
    automated:
      selfHeal: true

