apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alnav3/argocd-charts
    path: charts/homelab-apps/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-apps
  syncPolicy:
    automated:
      selfHeal: true

