matrix-synapse:
  serverName: 'alnav.dev'
  publicServerName: 'matrix.alnav.dev'
  argocd: true
  volumes:
    - name: mautrix-whatsapp-registration
      secret:
        secretName: mautrix-whatsapp-registration
        items:
          - key: mautrix-whatsapp-registration.yaml
            path: matrix-whatsapp-registration.yaml  # Specify the file in the secret

  volumeMounts:
    # Mount the mautrix-whatsapp-registration secret to /synapse/config/conf.d/
    - name: mautrix-whatsapp-registration
      mountPath: /synapse/config/conf.d/matrix-whatsapp-registration.yaml
      subPath: matrix-whatsapp-registration.yaml  # Mount the secret as a file in conf.d/

  extraConfig:
    app_service_config_files:
      - /synapse/data/media/matrix-whatsapp-registration.yaml


