matrix-synapse:
  serverName: 'alnav.dev'
  publicServerName: 'matrix.alnav.dev'
  argocd: true
  volumes:
    - name: mautrix-whatsapp-registration
      secret:
        secretName: mautrix-whatsapp-registration
        items:
          - key: mautrix-whatsapp-registration.yaml
            path: matrix-whatsapp-registration.yaml  # Use the key from the secret and path for the file

  volumeMounts:
    - name: mautrix-whatsapp-registration
      mountPath: /data/matrix-whatsapp-registration.yaml
      subPath: matrix-whatsapp-registration.yaml  # This ensures the file is mounted with the correct name


  extraConfig:
    app_service_config_files:
      - /data/mautrix-whatsapp-registration.yaml



