apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: splitweb-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: split.alnav.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: splitweb-service
            port:
              number: 80
