apiVersion: v1
kind: Secret
metadata:
  name: splitweb-secrets
type: Opaque
data:
  TURSO_DATABASE_URL: {{ .Values.TURSO_DATABASE_URL | b64enc | quote }}
  TURSO_AUTH_TOKEN: {{ .Values.TURSO_AUTH_TOKEN | b64enc | quote }}
  TURSO_JWT_SECRET: {{ .Values.TURSO_JWT_SECRET | b64enc | quote }}
