calibre-web:
  env:
    TZ: "America/New_York"

  persistence:
    config:
      enabled: true
      type: nfs
      path: /mnt/Storage/containers/calibre/config
      server: 10.71.71.19
      targetSelector:
        main:
          main:
            mountPath: /config
    books:
      enabled: true
      type: nfs
      path: /mnt/Storage/containers/calibre/books
      server: 10.71.71.19
      targetSelector:
        main:
          main:
            mountPath: /books

