calibre-web:
  env:
    TZ: "America/New_York"
  service:
    main:
      ports:
        main:
          port: 443
          protocol: https
          targetPort: 443

  persistence:
    config:
      enabled: true
      type: nfs
      path: /mnt/Storage/podVolumes/calibre/config
      server: 10.71.71.19
      targetSelector:
        main:
          main:
            mountPath: /config
    books:
      enabled: true
      type: pvc
      existingClaim: "calibre-books-pvc"

      #books:
      #  enabled: true
      #  type: nfs
      #  path: /mnt/Storage/podVolumes/calibre/books
      #  server: 10.71.71.19
      #  targetSelector:
      #    main:
      #      main:
      #        mountPath: /books

