calibre-web:
  env:
    TZ: "America/New_York"
  image:
    # -- image repository
    repository: ghcr.io/linuxserver/calibre-web
    # -- image tag
    tag: latest
    # -- image pull policy
    pullPolicy: IfNotPresent

  service:
    main:
      type: LoadBalancer
      loadBalancerIP: "10.71.71.199"
      ports:
        http:
          port: 8083

persistence:
  config:
    enabled: true
    mountPath: /config
    type: nfs
    path: /mnt/Storage/containers/calibre/config
    server: 10.71.71.19
    targetSelector:
      main:
        main:
          mountPath: /config
  books:
    enabled: true
    mountPath: /books
    type: nfs
    path: /mnt/Storage/containers/calibre/books
    server: 10.71.71.19
    targetSelector:
      main:
        main:
          mountPath: /books
  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        nginx.ingress.kubernetes.io/proxy-set-headers: "nginx-ingress-headers"
        nginx.ingress.kubernetes.io/proxy-set-header-Upgrade: "Upgrade"
        nginx.ingress.kubernetes.io/proxy-set-header-Connection: "upgrade"
        nginx.ingress.kubernetes.io/proxy-set-header-X-Forwarded-Host: "books.alnav.dev"
      hosts:
        - host: books.alnav.dev
          paths:
            - path: /
              pathType: Prefix
      tls: []  # Enable this if you want to add TLS/SSL support

