sonarr:
  metrics:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      targetSelector:
        main:
          main:
            mountPath: /config
          exportarr:
            mountPath: /config
            readOnly: true
    data:
      enabled: true
      type: nfs
      path: /mnt/Storage/Media
      server: 10.71.71.19
