jackett:
  persistence:
    config:
      enabled: true
      size: 10Gi
      targetSelector:
        main:
          main:
            mountPath: /config
          exportarr:
            mountPath: /config
            readOnly: true
