apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
data:
  secret_key: {{ .Values.secret_key | b64enc | quote }}
  postgres_password: {{ .Values.postgres_password | b64enc | quote }}
