apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
stringData:
  values.yaml: |
    postgresql:
      password: {{ .Values.postgres_password | quote }}
    authentik:
      postgresql:
        password: {{ .Values.postgres_password | quote }}
      secret_key: {{ .Values.secret_key | quote }}

