argo-cd:
  configs:
    cm:
      timeout.reconciliation: 20s
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  global:
    domain: argo.home
  server:
    ingress:
      ## If true, Prometheus server Ingress will be created
      enabled: true

      ## Prometheus server Ingress hostnames with optional path
      ## Must be provided if Ingress is enabled
      ##
    hosts:
      - argo.alnav.dev
    path: /
    extraArgs:
      - --insecure

