authentik:
    postgresql:
        auth:
            password: ENC[AES256_GCM,data:tJjBdagYu5w43H0r7mx0l8kCOQMyyGKY5XfbuKp2iiGt55yvtGPKjm2dll+lPRdB5bo=,iv:8mF7MmXWPyOdDGfM69CC5pGx/0AWPbM0mtF67I51g3g=,tag:2ynzfO98d9gzP6YJ7JJTjA==,type:str]
    authentik:
        postgresql:
            password: ENC[AES256_GCM,data:TbZSeOnECGd4y2Fof3zpN2Sy93adgaHOIvPdGuQgbpYRdiG0AGbtQCzeD03O4wf7zmc=,iv:viQnd+47Vy2t4sSB7mrI70Q2TRXOXATQmMPcgqTdUh4=,tag:Px+OO0Iw7Gvxi7YKfBpQqw==,type:str]
            postgresPassword: ENC[AES256_GCM,data:CSk021xmCDBDMDoIlYGeAYy9V2B+Jlfv8aG7atSj7A1zY7QQjly8RfmhqWhsXYTtPDk=,iv:6R5RuW3ZP50yOkffYsbiOZB6URETaG9CqL9ERk2W1Vg=,tag:Fhj7kqDginnUWiG6UnghgQ==,type:str]
        secret_key: ENC[AES256_GCM,data:JhA/isS1rdX+dGZ1YjSQRBnmmjzOh2QgAsJdK/dhMcv/5y4HHYAq89zFnGPFaUXqoXs=,iv:eiLVi2R6QRMam2+XFtC1IeJA/sJtqbHWGkrPN2nHWeg=,tag:p3299Lb5lIgjy2owXf0Ayw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtvjq4r4l7kkx444q9w6ca35ewh37sl5gtfepa77gfnfyp5xgu8stg9yt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZXZUSnhzZ1RDRk1MNVpV
            Q2FmRmhtVGgvN01zZmtRMmpTUWZqcklvOVhvClVoU1MvT3gxMnh3ZWtpR2dUdmkx
            UURXbGd2NzVLY3grVkNldTVOdGJYWVUKLS0tIFVzVzljUFpDUTA4d1R2aFVDdXFk
            QUZaeEJsdCt6SXY1akt4UFEwS0V2WXcKqA3D1eWwnGK+edhDXgQ8qsaozCMpEd4h
            geUKLtgK6l8lLniUnKfBnAvugAArWhk2fZvh33AuLrOLfpHh/SxSlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T22:23:32Z"
    mac: ENC[AES256_GCM,data:7nvkjJ3VXCX2lCulZ4OmElIUUmrXDSBKCX05Zp4fJHadukP1XZtIXPP2x03ZWBC8yCvJXxf8BTvtVSB5zNy7su8SXXa0cGZkw5m1MA6JV5fcFIbYLd8xokIK01HixcneNMh6pMNIqGs04TY5NkK68+LTZ/z+s1AlxXPN95VvP30=,iv:Ji0DCZYxciIj+Zcu4bh5gEg+8AxS5huFPSN8KQMTNhE=,tag:keN+Ba64/Lo8A7duP/GEDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
