authentik:
  global:
    envFrom:
    - secretRef:
        name: authentik-secrets
  server:
    ingress:
      ingressClassName: nginx-internal
      enabled: true
      hosts:
        - auth.alnav.dev
  postgresql:
    enabled: true

  redis:
    enabled: true

