authentik:
  authentik:
      secret_key: file:///authentik-secrets/secret_key
      postgresql:
          password: file:///authentik-secrets/postgres_password

  worker:
      volumes:
        - name: authentik-secrets
          secret:
            secretName: authentik-secrets
      volumeMounts:
        - name: authentik-secrets
          mountPath: /authentik-secrets
          readOnly: true
  server:
      volumes:
        - name: authentik-secrets
          secret:
            secretName: authentik-secrets
      volumeMounts:
        - name: authentik-secrets
          mountPath: /authentik-secrets
          readOnly: true
      ingress:
          # Specify kubernetes ingress controller class name
          ingressClassName: nginx-internal
          enabled: true
          hosts:
              - auth.alnav.dev

  postgresql:
      enabled: true
      auth:
          username: authentik
          password: file:///authentik-secrets/postgres_password
          postgresPassword: file:///authentik-secrets/postgres_password
  redis:
      enabled: true
