authentik:
  authentik:
      secret_key: "PleaseGenerateASecureKey"
      postgresql:
          password: "ThisIsNotASecurePassword"

  server:
      ingress:
          # Specify kubernetes ingress controller class name
          ingressClassName: nginx-internal
          enabled: true
          hosts:
              - auth.alnav.dev

  postgresql:
      enabled: true
      auth:
          password: "ThisIsNotASecurePassword"
  redis:
      enabled: true
