pihole:
  persistedVolumeClaim:
    enabled: true
  DNS1:
    10.71.71.1
  DNS2:
    9.9.9.9

  ingress:
    enabled: true
    hosts:
      - "pihole.home"

  serviceWeb:
    loadBalancerIP: 10.71.71.250
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  serviceDns:
    loadBalancerIP: 10.71.71.250
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  replicaCount: 1

external-dns:
  provider: pihole
  policy: upsert-only
  txtOwnerId: "homelab"
  pihole:
    server: http://pihole-web.pihole-system.svc.cluster.local
  extraEnvVars:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: password
  serviceAccount:
    create: true
    name: "external-dns"
  ingressClassFilters:
    - nginx-internal

