jellyfin:
  image:
    tag: "latest"
  env:
    NVIDIA_VISIBLE_DEVICES: all
    NVIDIA_DRIVER_CAPABILITIES: all

  extraArgs: ["--runtime=nvidia"]

  ingress:
    enabled: true
    hosts:
      - host: jellyfin.home
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: jellyfin.alnav.dev
        paths:
          - path: /
            pathType: ImplementationSpecific

  persistence:
    config:
      enabled: true
      isPvc: false  # Deshabilitar el uso de PVC
      customVolume:
        hostPath:
          path: "/media/Jellyfin/config"  # Especifica la ruta en tu nodo

    data:
      enabled: true
      isPvc: false  # Deshabilitar el uso de PVC
      customVolume:
        hostPath:
          path: "/media/Jellyfin/media"  # Especifica otra ruta en tu nodo para datos (si necesario)


  replicaCount: 1  # Asegúrate de que solo una réplica esté corriendo

  service:
    port: 8096
    type: LoadBalancer  # Use LoadBalancer to assign an external IP
    loadBalancerIP: "10.71.71.200"


  volumeMounts:
    - name: "render-device"
      mountPath: "/dev/dri/renderD128"
  volumes:
    - name: "render-device"
      hostPath:
        path: "/dev/dri/renderD128"

