jellyfin:
  image:
    tag: "latest"

  securityContext:
    privileged: true
  ingress:
    enabled: true
    hosts:
      - host: jellyfin.home
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: jellyfin.alnav.dev
        paths:
          - path: /
            pathType: ImplementationSpecific


  persistence:
    config:
      enabled: false

    data:
      enabled: false


  replicaCount: 1  # Asegúrate de que solo una réplica esté corriendo

  service:
    port: 8096
    type: LoadBalancer  # Use LoadBalancer to assign an external IP
    loadBalancerIP: "10.71.71.200"

  volumes:
    - name: "render-device"
      hostPath:
        path: "/dev/dri/renderD128"
    - name: jellyfin-config
      hostPath:
        path: "/media/Jellyfin/config"  # Path on your node for config data
    - name: jellyfin-media
      hostPath:
        path: "/media/Jellyfin/media"  # Path on your node for media data

  # -- Additional volume mounts for the Jellyfin container.
  volumeMounts:
    - name: "render-device"
      mountPath: "/dev/dri/renderD128"
    - name: jellyfin-config
      mountPath: "/config"  # Path where config will be mounted in the container
      readOnly: true
    - name: jellyfin-media
      mountPath: "/media"  # Path where media will be mounted in the container

