jellyfin:
  image:
    tag: "latest"

  securityContext:
    privileged: true
  ingress:
    enabled: true
    hosts:
      - host: jellyfin.home
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: jellyfin.alnav.dev
        paths:
          - path: /
            pathType: ImplementationSpecific

  resources:
   limits:
     gpu.intel.com/i915: "1"
   requests:
     gpu.intel.com/i915: "1"

  persistence:
    config:
      enabled: false

    data:
      enabled: false


  replicaCount: 1  # Asegúrate de que solo una réplica esté corriendo

  service:
    port: 8096
    type: LoadBalancer  # Use LoadBalancer to assign an external IP
    loadBalancerIP: "10.71.71.200"

  volumes:
    - name: jellyfin-config
      hostPath:
        path: "/media/Jellyfin/config"  # Path on your node for config data
    - name: jellyfin-media
      hostPath:
        path: "/media/Jellyfin/media"  # Path on your node for media data
    - name: transcoding
      hostPath:
        path: "/media/Jellyfin/transcoding"  # Path on your node for media data

  # -- Additional volume mounts for the Jellyfin container.
  volumeMounts:
    - name: jellyfin-config
      mountPath: "/configReal"  # Path where config will be mounted in the container
    - name: jellyfin-media
      mountPath: "/mediaReal"  # Path where media will be mounted in the container
    - name: transcoding
      mountPath: /transcode

