immich:
  cnpg:
    main:
      enabled: true

  persistence:
    library:
      enabled: true
      existingClaim: "immich-upload-pvc"
      mountPath: /usr/src/app/upload/library
      subPath: library
      targetSelector:
        main:
          main: {}
        microservices:
          microservices: {}

    uploads:
      enabled: true
      existingClaim: "immich-upload-pvc"
      mountPath: /usr/src/app/upload/upload
      subPath: upload
      targetSelector:
        main:
          main: {}
        microservices:
          microservices: {}

    backups:
      enabled: true
      existingClaim: "immich-upload-pvc"
      mountPath: /usr/src/app/upload/backups
      subPath: backups
      targetSelector:
        main:
          main: {}
        microservices:
          microservices: {}

    thumbs:
      enabled: true
      existingClaim: "immich-upload-pvc"
      mountPath: /usr/src/app/upload/thumbs
      subPath: thumbs
      targetSelector:
        main:
          main: {}
        microservices:
          microservices: {}

    profile:
      enabled: true
      existingClaim: "immich-upload-pvc"
      mountPath: /usr/src/app/upload/profile
      subPath: profile
      targetSelector:
        main:
          main: {}
        microservices:
          microservices: {}

    video:
      enabled: true
      existingClaim: "immich-upload-pvc"
      mountPath: /usr/src/app/upload/encoded-video
      subPath: encoded-video
      targetSelector:
        main:
          main: {}
        microservices:
          microservices: {}
