immich:
  metrics:
    main:
      enabled: false
  persistence:
    library:
      enabled: true
      type: nfs
      path: /mnt/Storage/Media
      server: 10.71.71.19
      targetSelector:
        main:
          main:
            mountPath: /library
    uploads:
      enabled: true
      type: nfs
      path: /mnt/Storage/things
      server: 10.71.71.19
      targetSelector:
        main:
          main:
            mountPath: /postgres
