immich:
  persistence:
    upload:
      enabled: true
      mountPath: /usr/src/app/upload
      existingClaim: "immich-upload-pvc" # Nombre del PVC existente para config
      size: 300Gi
      #storageClass: "longhorn"  # Replace with your storage class
      accessMode: ReadWriteOnce

