immich:
  persistence:
    library:
      enabled: true
      type: emptyDir
      mountPath: /usr/src/app/upload/library
      targetSelector:
        # Main pod/container is server
        main:
          main: {}
        microservices:
          microservices: {}
    uploads:
      enabled: true
      type: emptyDir
      mountPath: /usr/src/app/upload/upload
      targetSelector:
        # Main pod/container is server
        main:
          main: {}
        microservices:
          microservices: {}
    backups:
      enabled: true
      type: emptyDir
      mountPath: /usr/src/app/upload/backups
      targetSelector:
        # Main pod/container is server
        main:
          main: {}
        microservices:
          microservices: {}
    thumbs:
      enabled: true
      type: emptyDir
      mountPath: /usr/src/app/upload/thumbs
      targetSelector:
        # Main pod/container is server
        main:
          main: {}
        microservices:
          microservices: {}
    profile:
      enabled: true
      type: emptyDir
      mountPath: /usr/src/app/upload/profile
      targetSelector:
        # Main pod/container is server
        main:
          main: {}
        microservices:
          microservices: {}
    video:
      enabled: true
      type: emptyDir
      mountPath: /usr/src/app/upload/encoded-video
      targetSelector:
        # Main pod/container is server
        main:
          main: {}
        microservices:
          microservices: {}
    upload:
      enabled: true
      mountPath: /usr/src/app/upload
      existingClaim: "immich-upload-pvc" # Nombre del PVC existente para config
      size: 300Gi
      #storageClass: "longhorn"  # Replace with your storage class
      accessMode: ReadWriteOnce

