searxng:
  # -- Configure the ingresses for the chart here.
# Additional ingresses can be added by adding a dictionary key similar to the 'main' ingress.
# @default -- See below
ingress:
  #secondary:
  #  enabled: true
  #  primary: false

  #  # -- Provide additional annotations which may be required.
  #  annotations:
  #    kubernetes.io/ingress.class: nginx-internal

  #  ingressClassName:  "nginx-internal"

  #  ## Configure the hosts for the ingress
  #  hosts:
  #      host: search.home
  #      ## Configure the paths for the host
  #      paths:
  #        -  # -- Path.  Helm template can be passed.
  #          path: /
  #          # -- Ignored if not kubeVersion >= 1.14-0
  #          pathType: Prefix

  #  tls: []
  main:
    enabled: true
    primary: false

    # -- Provide additional annotations which may be required.
    annotations:
      kubernetes.io/ingress.class: nginx-external

    ingressClassName:  "nginx-external"

    ## Configure the hosts for the ingress
    hosts:
        host: search.alnav.dev
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix

    tls: []

