apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torrent-ingress-external
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 500M
spec:
  rules:
  - host: torrent.alnav.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torrent-transmission
            port:
              number: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torrent-ingress-internal
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: torrent.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torrent-transmission
            port:
              number: 9091

