apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautrix-whatsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautrix-whatsapp
  template:
    metadata:
      labels:
        app: mautrix-whatsapp
    spec:
      containers:
      - name: mautrix-whatsapp
        image: "dock.mau.dev/mautrix/whatsapp:latest"
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - containerPort: 29318
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mautrix-whatsapp-pvc
      restartPolicy: Always
