apiVersion: v1
kind: Service
metadata:
  name: mautrix-whatsapp-service
spec:
  selector:
    app: mautrix-whatsapp
  ports:
    - protocol: TCP
      port: 29318
      targetPort: 29318
  publishNotReadyAddresses: true

