apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jellyfin.alnav.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin-service
            port:
              number: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: default
spec:
  type: ExternalName
  externalName: 10.71.71.40
  ports:
  - port: 8096
    targetPort: 8096
    protocol: TCP


